verbose: false
logType: '{{ envVars.logType }}'
server:
  debug: false
  routes:
    state:
      failAction: 'ignore'
  port: "{{ envVars.port }}"
  address: '0.0.0.0'
routePrefix: "{{ envVars.routePrefix }}"
plugins:
  hapi-config-route:
    _enabled: '{{ truthy(envVars.configKey) }}'
    key: '{{envVars.configKey}}'
  hapi-health:
    token: "{{ envVars.healthToken }}"
    endpoint: "{{routePrefix}}/health"
  hapi-logr:
    reporters:
      flat:
        reporter: 'logr-flat'
        options:
          timestamp: false
          appColor: true
          enabled: '{{logType === "flat"}}'
          theme:
            keys: 'cyan'
          tagColors:
            redirect: 'bgBlue'
            not-found: 'bgBlue'
            user-error: 'bgYellow'
            server-error: 'bgRed'
      consoleColor:
        reporter: 'logr-console-color'
        options:
          enabled: '{{logType === "cli"}}'
          timestamp: false
          appColor: true
      bell:
        reporter: 'logr-reporter-bell'
        options:
          enabled: '{{logType === "cli"}}'
  hapi-timing:
    _enabled: "{{ envVars.timing }}"
    threshold: '{{ envVars.threshold }}'
  hapi-cache-stats:
    interval: '{{ envVars.cacheStatsInterval }}'
    _enabled: '{{ truthy(envVars.cacheStatsInterval) }}'
    verbose: '{{ truthy(envVars.cacheStatsVerbose) }}'
  hapi-oppsy:
    _enabled: '{{ truthy(envVars.opsInterval) }}'
    interval: '{{ envVars.opsInterval }}'
    logCpu: false
    logMemory: false
  "@firstandthird/hapi-require-https":
    _enabled: '{{ envVars.forceHttps }}'
  hapi-method-loader:
    cwd: '{{CWD}}'
    verbose: '{{verbose}}'
  hapi-route-loader:
    _dependencies:
      - 'hapi-method-loader'
    cwd: '{{CWD}}'
    prefix: '{{routePrefix}}'
    verbose: '{{verbose}}'
  hapi-log-response:
    requests: '{{ envVars.logRequests }}'
    _dependencies:
      - 'hapi-trailing-slash'
    tags:
      - 'detailed-response'
  hapi-trailing-slash:
    method: 'remove'
