verbose: true
logType: '{{ENV.LOG_TYPE || "flat" }}'
server:
  debug: false
connection:
  port: "{{ENV.PORT || 8080}}"
  address: '0.0.0.0'
routePrefix: "{{ ENV.PATH_PREFIX }}"
plugins:
  hapi-trailing-slash:
    method: 'remove'
  hapi-method-loader:
    _priority: 2
    cwd: '{{CWD}}'
    verbose: '{{verbose}}'
  hapi-route-loader:
    _priority: 3
    cwd: '{{CWD}}'
    prefix: '{{routePrefix}}'
    verbose: '{{verbose}}'
  hapi-logr:
    _priority: -5
    clientErrorsToWarnings: true
    requests: '{{!!ENV.ACCESS_LOGS || false}}'
    reporters:
      flat:
        reporter: 'logr-flat'
        options:
          timestamp: false
          appColor: true
          enabled: '{{logType === "flat"}}'
      consoleColor:
        reporter: 'logr-console-color'
        options:
          enabled: '{{logType==="cli"}}'
          timestamp: false
          appColor: true
      bell:
        reporter: 'logr-reporter-bell'
        options:
          enabled: '{{logType==="cli"}}'
  hapi-log-response:
    tags:
      - 'detailed-response'
