verbose: false
logType: '{{ENV.LOG_TYPE || "flat" }}'
server:
  debug: false
  routes:
    state:
      failAction: 'ignore'
  port: "{{ENV.PORT || 8080}}"
  address: '0.0.0.0'
routePrefix: "{{ ENV.ROUTE_PREFIX || ENV.PATH_PREFIX || '' }}"
plugins:
  hapi-timing:
    _enabled: '{{ ENV.TIMING === 1 }}'
    threshold: '{{ ENV.SLOW_THRESHOLD || 300 }}'
  hapi-cache-stats:
    interval: 600000
  hapi-oppsy:
    interval: 60
    logCpu: false
    logMemory: false
  hapi-logr:
    reporters:
      flat:
        reporter: 'logr-flat'
        options:
          timestamp: false
          appColor: true
          enabled: '{{logType === "flat"}}'
          theme:
            keys: 'cyan'
      consoleColor:
        reporter: 'logr-console-color'
        options:
          enabled: '{{logType === "cli"}}'
          timestamp: false
          appColor: true
      bell:
        reporter: 'logr-reporter-bell'
        options:
          enabled: '{{logType === "cli"}}'
  "@firstandthird/hapi-require-https":
    _enabled: '{{ENV.FORCE_HTTPS === "true"}}'
  hapi-method-loader:
    cwd: '{{CWD}}'
    verbose: '{{verbose}}'
  hapi-route-loader:
    _dependencies:
      - 'hapi-method-loader'
    cwd: '{{CWD}}'
    prefix: '{{routePrefix}}'
    verbose: '{{verbose}}'
  hapi-log-response:
    requests: '{{ENV.ACCESS_LOGS === "true" || ENV.ACCESS_LOGS === true }}'
    _dependencies:
      - 'hapi-trailing-slash'
    tags:
      - 'detailed-response'
  hapi-trailing-slash:
    method: 'remove'
