verbose: false
server:
  debug: false
connection:
  port: "{{ENV.PORT || 1234}}"
  address: '0.0.0.0'
plugins:
  hapi-logr:
    _priority: -5
    type: 'console'
    renderOptions:
      console:
        timestamp: false
        flat: true
      json:
        additional:
          hostname: '{{ENV.HOSTNAME}}'
        tagsObject: true
  hapi-method-loader:
    _priority: 2
    cwd: '{{CWD}}'
    verbose: '{{verbose}}'
  hapi-route-loader:
    _priority: 3
    cwd: '{{CWD}}'
    verbose: '{{verbose}}'
